### ISSUE TITLE
Humidity compensation

### ISSUE THREAD

**Issue by bachi76** [Sensirion/arduino-ess#12]
Hi,
It would be great if humidity compensation using an rH value could be added soon.
How about?

**Comment by abrauchli** [comment]
Hi @bachi76 
Indeed and thanks for the suggestion. In the meantime check out the generic driver (it can be used on Arduino) on https://github.com/Sensirion/embedded-sgp where humidity compensation is possible. The svm30 branch (https://github.com/Sensirion/embedded-sgp/tree/svm30/svm30) has conversion code for RH/T->AH.

We'll leave the issue open to track progress.

**Comment by bachi76** [comment]
Hello @abrauchli - thanks for the quick response - will check!
